name: Build & publish coverage-plugin
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  build_and_publish:
    name: Publish coverage plugin as zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Check and build
        run: gradle -Pversion=${GITHUB_REF:11} build
      - name: Publish to Maven
        run: gradle -Pversion=${GITHUB_REF:11} publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      - name: Publish to NPM
        run: |
          cd build/distributions/npm
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
